name: Fluxo de Trabalho

on:
  push:
    branches:
      - main

jobs:
  mensagem:
    name: Exibir Mensagem
    runs-on: windows-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Exibir Mensagem
      run: echo "Um push foi feito na branch main."
